
#---------------------------------------------------------------MONTHLY ELECTRIC BILL------------------------------------------------------------------------------

def month_elbill(): 
    global month_elbill 

    month_elbill = int(input("Enter your electric monthly bill:  \n"))

try : 

            month_elbill = int(input("Enter your electric monthly bill:  \n"))                  
            a = month_elbill * 105
            print(a)
except:                                                                                         
            print("Enter integer values") 
            month_elbill() 
            month_elbill = int(input("Enter your electric monthly bill:  \n"))
            a = month_elbill * 105
            print(a)

#---------------------------------------------------------------MONTHLY GAS------------------------------------------------------------------------------

def month_gas(): 
        global month_gas 

        month_gas = int(input("Enter your monthly gas:  \n"))

try : 

        month_gas = int(input("Enter your monthly gas:  \n"))
        b = month_gas * 105
        
except: 
        print("Enter integer values") 
        month_gas()  
        month_gas = int(input("Enter your monthly gas:  \n"))
        b = month_gas * 105
        
#---------------------------------------------------------------MONTHLY OIL------------------------------------------------------------------------------
def month_oil(): 
        global month_oil 

        month_oil = int(input("Enter your monthly oil:  \n"))

try : 

        month_oil = int(input("Enter your monthly oil:  \n"))
        c = month_oil * 113
        
except: 
        print("Enter integer values") 
        month_oil() 
        month_oil = int(input("Enter your monthly oil:  \n"))
        c = month_oil * 113
        
#---------------------------------------------------------------YEARLY CAR MIL------------------------------------------------------------------------------

def year_car(): 
        global year_car 

        year_car = int(input("Enter your yearly mileage on your car:  \n"))
try : 

        year_car = int(input("Enter your yearly mileage on your car:  \n"))
        d = year_car * 0.79
        
except: 
        print("Enter integer values") 
        year_car() 
        year_car = int(input("Enter your yearly mileage on your car:  \n"))
        d = year_car * 0.79

#---------------------------------------------------------------FLIGHTS 4H AND LESS------------------------------------------------------------------------------
def n_flights_l4h(): 
        global n_flights_l4h 

        n_flights_l4h = int(input("Enter number of flights you've taken in the past year for 4 hours or less:  \n"))
try : 

        n_flights_l4h = int(input("Enter number of flights you've taken in the past year for 4 hours or less:  \n"))
        e = n_flights_l4h * 1100
        
except: 
        print("Enter integer values") 
        n_flights_l4h() 
        n_flights_l4h = int(input("Enter number of flights you've taken in the past year for 4 hours or less:  \n"))
        e = n_flights_l4h * 1100

#---------------------------------------------------------------FLIGHTS 4H AND MORE------------------------------------------------------------------------------
def n_flights_m4h(): 
        global n_flights_m4h 

        n_flights_m4h = int(input("Enter number of flights you've taken in the past year for 4 hours or more:  \n"))
try : 

        n_flights_m4h = int(input("Enter number of flights you've taken in the past year for 4 hours or more:  \n"))
        e = n_flights_m4h * 4400
        
except: 
        print("Enter integer values") 
        n_flights_m4h() 
        n_flights_m4h = int(input("Enter number of flights you've taken in the past year for 4 hours or more:  \n"))
        e = n_flights_m4h * 4400


add = a + b + c + d + e 
#print(add1)

#---------------------------------------------------------------NEWSPAPER RECYCLE------------------------------------------------------------------------------

newspaper = input("Do you recycle newspaper? [Y]es / [N]o\n ")
 
if (newspaper == "N" or "no" or "NO" or "No"):
     add = add + 184
     #print(add)

#---------------------------------------------------------------ALUMINUM AND TIN RECYCLE------------------------------------------------------------------------------

al_tin = input("Do you recycle aluminum and tin? [Y]es / [N]o\n ")

if (al_tin == "N" or "no" or "NO" or "No"):
     add = add + 166
     print(add)



if (add<15000):

    print("You have a low carbon footprint! :)")

elif(add <22000 and add >16000):
    print("You have an average carbon footprint...\n\n ")
    print("A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions.\n\n --------------------------------------HERE ARE SOME SOLUTIONS TO REDUCE YOUR CARBON FOOTPRINT-----------------------------------------\n \n 1. Hang out the washing instead of tumble drying \n 2. Turn down the heating by 1⁰C \n 3. Only fill the kettle with the amount of water you need to boil \n 4. Spend less time in the shower\n 5. Turn electrical equipment off when not in use \n 6. Travel less and travel more carbon footprint friendly \n \n ----from : https://www.carbonfootprint.com/minimisecfp.html")

elif (add>22000):
    print("Unfortunately you have a high carbon footprint. :(\n \n ")
    print("A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions.\n \n--------------------------------------HERE ARE SOME SOLUTIONS TO REDUCE YOUR CARBON FOOTPRINT-----------------------------------------\n \n 1. Hang out the washing instead of tumble drying \n 2. Turn down the heating by 1⁰C \n 3. Only fill the kettle with the amount of water you need to boil \n 4. Spend less time in the shower\n 5. Turn electrical equipment off when not in use \n 6. Travel less and travel more carbon footprint friendly \n \n ----from : https://www.carbonfootprint.com/minimisecfp.html")
